### PR TITLE
Remix v2

### PR DESCRIPTION
**Pull request by edgesoft**
Update to work with remix v.2

https://github.com/pbteja1998/remix-auth-email-link/discussions/41

### CODE REVIEW

**Comment by pbteja1998** [comment]
@edgesoft Have you tested this locally and everything works fine?

Also, please don't do the version bump here. I will be doing it separately.

**Comment by edgesoft** [comment]
@pbteja1998 I have tested it in my application and getting mail and can both login and logout.

**Comment by pbteja1998** [comment]
Thank you @edgesoft. 

Released in `v2.1.0`. 

If possible, can you please install the latest version and let me know if everything looks good on your end?

**Comment by edgesoft** [comment]
> Thank you @edgesoft.
> 
> Released in `v2.1.0`.
> 
> If possible, can you please install the latest version and let me know if everything looks good on your end?

@pbteja1998 Everything works great! Thanks! Running on 2.1.0 now.

**Comment by ericallam** [comment]
@pbteja1998 this PR made `yarn` a dependency of this library, which I'm guessing was not intended.

**Comment by pbteja1998** [comment]
@ericallam Thanks. Removed it as a dependency.

**Pull request merged**
